### ISSUE TITLE
Links down

### ISSUE THREAD

**Issue by lchicay** [usnish/biochemical-pathways-poster#1]
hey usnish,

could you please provide new links for the high-quality image? The dropbox link is not working. Thanks so much for this, it will be very useful in my studies. If I knew something about Python I would run the script and do this by myself, but I can't  :/

**Comment by usnish** [comment]
Ah, looks like part of the script broke as well. 

Dropbox seems to have taken down their public folder service (perhaps due to the high bandwidth driven through people like me who used this service as lazy static hosting). 

I'll upload those links elsewhere. In the meantime, here's a placeholder link to the hires file on Google Drive: https://drive.google.com/file/d/0B3dhFcBi_Sr0UzJBTUl1c2k1UDQ/view?usp=sharing
